@extends('layouts.Nav')

@section('page')
<i class="fas fa-user"></i> Create Book
@endsection

@section('path')
Users / New User
@endsection

@section('content')
<?php $random = 'RA-'.rand(0,1).''.rand();?>
<form method="post"  action="{{route('CreateEvent')}}" enctype= "multipart/form-data"  style="font-size: 15px">
  {{ csrf_field() }}

<div class="container-fluid" id="container-wrapper">



<div class="msg">

</div>


          <div class="row mb-3">
  

           
            <!-- Pie Chart -->
    




 <!-- Area Chart -->
            <div class="col-xl-8 col-lg-7">
                        <?php  if(isset($_REQUEST['msg'])){ ?>
                             <div class="alert alert-success" role="alert">
<B>Success</B> New Events has been posted.</div>
                <?php } else{ } ?>
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between text-light" style="background-color: #6B80FB">
                  <h6 class="m-0 font-weight-bold">Book Information</h6>
                </div>
                <div class="card-body">
                  

  <div class="form-row">
    <div class="col-md-12 mb-1">
            <label for="Ref">Reference:  <span style="color: red">*</span>   (A reference is pre-generated by the system for the new user.)</label>
<a onclick="RefreshReference()" style="float: right"><i class="fas fa-sync-alt" style="color: lightgreen"></i></a>
<input type="text" class="form-control " name="Ref" id="Ref" value="<?php echo $random?>" readonly>
</div></div>

<br>
  <div class="form-row">
    <div class="col-md mb">
      <label for="Title">Title <span style="color: red">*</span></label>
      <input type="text" class="form-control @error('Title') is-invalid @enderror" name="Title" id="Title" placeholder="" value="{{ old('Title') }}" >
      <div class="ErrName feed">
       
@error('Title')
{{$message}}
@enderror 
      </div>
    </div>
</div>

<br>

  <div class="form-row">

   <div class="col-md mb-1">
      <label for="Abstract">Abstract <span style="color: red">*</span></label>
      <textarea type="textarea" class="form-control @error('Abstract') is-invalid @enderror" name="Abstract" id="Abstract" placeholder="" value="{{old('Abstract')}}"></textarea>
      <div class="ErrTel feed">
@error('Abstract')
{{$message }}
@enderror
      </div>
    </div>

   <div class="col-md mb-1">
      <label for="Introduction">Introduction <span style="color: red">*</span></label>
      <textarea  class="form-control @error('Introduction') is-invalid @enderror" name="Introduction" id="Introduction" placeholder="" value="{{old('Introduction')}}"></textarea>
      <div class="ErrTel feed">
@error('Introduction')
{{$message }}
@enderror
      </div>
    </div>
  </div>


<br>



















  <div class="form-row">

    <div class="col-md mb">
      <label for="Title">Authors <span style="color: red">*</span></label>
      <input type="text" class="form-control @error('Authors') is-invalid @enderror" name="Authors" id="Authors" placeholder="" value="{{ old('Authors') }}" >
      <div class="ErrName feed">
       
@error('Authors')
{{$message}}
@enderror 
      </div>
    </div>


    <div class="col-md mb">
      <label for="Title">Type <span style="color: red">*</span></label>
 <select class="form-control @error('type') is-invalid @enderror" name="type" id="type">
    <option value="" selected>Type ...</option>
    <option value="Conference" >Conference</option>
    <option value="Books">Books</option>
    <option value="Journals and Magazines">Journals & Magazines</option>
    <option value="Articles">Articles</option>
    <option value="Papers">Papers</option>
  </select>
 <div class="ErrName feed">  
@error('type')
{{$message}}
@enderror 
      </div>
    </div>



    <div class="col-md mb">
      <label for="Title">Publisher <span style="color: red">*</span></label>
 <select class="form-control @error('publishers') is-invalid @enderror" name="publishers" id="publishers">
    <option value="" selected>Publisher..</option>
    <option value="IEEE" >IEEE</option>
    <option value="DirectScience">DirectScience</option>
  </select>
 <div class="ErrName feed">  
@error('publishers')
{{$message}}
@enderror 
      </div>
    </div>


  </div> 

<br>















  <div class="form-row">

<div class="col-md mb">
  <label for="Title">Themes <span style="color: red">*</span></label>
 <select class="form-control @error('themes') is-invalid @enderror" id="themes" name="themes">
    <option value="" selected>Theme...</option>
    <option value="Computing and Processing" >Computing and Processing</option>
    <option value="Communication">Communication</option>
    <option value="Logistic and Transport">Logistic and Transport</option>
    <option value="Business and Economics">Business and Economics</option>
    <option value="Engineering">Engineering</option>
    <option value="Medical">Medical</option>
  </select>
 <div class="ErrName feed">  
@error('themes')
{{$message}}
@enderror 
      </div>
</div>



<div class="col-md mb">
  <label for="Title">Topics <span style="color: red">*</span></label>
 <select class="form-control @error('topics') is-invalid @enderror" name="topics" id="topics">
  <option value="" selected>Topics...</option>
    <option value="Software Engineering">Software Engineering</option>
    <option value="Physics">Physics</option>
    <option value="Medical Ontology">Medical Ontology</option>
    <option value="Artificial intelligence">Artificial intelligence</option>
    <option value="Theory of computation">Theory of computation</option>
    <option value="Computer networks">Computer networks</option>
    <option value="Computer security in cryptography">Computer security in cryptography</option>
    <option value="Accounting">Accounting</option>
    <option value="Marketing">Marketing</option>
    <option value="Finance">Finance</option>
    <option value="Human resources">Human resources</option>
    <option value="Economics">Economics</option>
    <option value="Sociology">Sociology</option>
    <option value="Tourism Studies">Tourism Studies</option>
    <option value="International Relations">International Relations</option>
    <option value="Chemistry">Chemistry</option>
    <option value="Biology">Biology</option>
    <option value="Physics">Physics</option>
    <option value="Physics">Physics</option>
  </select>
  </select>
 <div class="ErrName feed">  
@error('topics')
{{$message}}
@enderror 
      </div>
</div>


<div class="col-md mb">
      <label for="Title">Price <span style="color: red">*</span></label>
      <input type="text" class="form-control @error('price') is-invalid @enderror" name="price" id="price" placeholder="" value="{{ old('price') }}" >
      <div class="ErrName feed">
       
@error('price')
{{$message}}
@enderror 
      </div>

</div>
</div>
<br>


  <div class="form-row">

<div class="col-md mb">
  <label for="Title">Year <span style="color: red">*</span></label>
 <select class="form-control @error('yearP') is-invalid @enderror" name="yearP" id="yearP">
    <option value="">Year...</option>
    <option value="2022">2022</option>
    <option value="2021">2021</option>
    <option value="2020">2020</option>
    <option value="2019">2019</option>
    <option value="2018">2018</option>
    <option value="2017">2017</option>
    <option value="2016">2016</option>
    <option value="2015">2015</option>
    <option value="2014">2014</option>
    <option value="2013">2013</option>
    <option value="2012">2012</option>
    <option value="2011">2011</option>
    <option value="2010">2010</option>
    <option value="2009">2009</option>
    <option value="2008">2008</option>
    <option value="2007">2007</option>
    <option value="2006">2006</option>
    <option value="2005">2005</option>
    <option value="2004">2004</option>
    <option value="2003">2003</option>
    <option value="2002">2002</option>
    <option value="2001">2001</option>
    <option value="2000">2000</option>
    <option value="1999">1999</option>
    <option value="1998">1998</option>
    <option value="1997">1997</option>
    <option value="1996">1996</option>
    <option value="1995">1995</option>
    <option value="1994">1994</option>
   

  </select>
      <div class="ErrName feed">
       
@error('yearP')
{{$message}}
@enderror 
      </div>
</div>





<div class="col-md mb">
      <label for="Title">Pages <span style="color: red">*</span></label>
      <input type="text" class="form-control @error('page') is-invalid @enderror" name="page" id="page" placeholder="" value="{{ old('page') }}" >
      <div class="ErrName feed">
       
@error('page')
{{$message}}
@enderror 
      </div>

</div>



<div class="col-md mb">
      <label for="Title">Chapter <span style="color: red">*</span></label>
      <input type="text" class="form-control @error('Chapter') is-invalid @enderror" name="Chapter" id="Chapter" placeholder="" value="{{ old('Chapter') }}" >
      <div class="ErrName feed">
       
@error('Chapter')
{{$message}}
@enderror 
      </div>

</div>










<div class="col-md mb">
        <label for="Title">Core <span style="color: red">*</span></label>

 <select class="form-control @error('core') is-invalid @enderror" name="core" id="core">
  <option value="">Core...</option>
  <option value="Hardcore">Hardcore</option>
  <option value="Papercore">Papercore</option>

  </select>
     <div class="ErrName feed">
       
@error('core')
{{$message}}
@enderror 
      </div>
</div>

</div>

  </div>



</div>







       <br>         







<hr>
<center><button class="btn" id="save" style="width: 100px;background-color: #1270fc;color: white" type="submit"><i class="fas fa-plus-square"></i> Save</button>
 <a href="{{route('product')}}" style="width: 100px;" class="btn btn-danger"><i class="fas fa-arrow-left"></i> Back</a></center>




                </div>

<div class="card-footer text-center" style="background-color: #6B80FB">
      
    </div>  </div>
 </div>


              </div>
            </div>















</div>


                    </form>

  <button type="button" class="btn btn-primary" id="showdata" data-toggle="modal" data-target="#notif" ></button>

<script type="text/javascript">


</script>
@endsection
